"use client";

import { useState } from "react";
import { Button } from "~/components/ui/button";
import { Card } from "~/components/ui/card";
import { Play, Pause } from "lucide-react";
import Link from "next/link";
export default function DemoSection() {
  const [playingId, setPlayingId] = useState<string | null>(null);
  const naturalSpeechSamples = [
    {
      id: "friendly-female",
      text: "Hi there! I'm excited to help you create amazing voice content today.",
      voiceType: "Warm Female",
      audioUrl: "/audio/friendly-female.wav",
    },
    {
      id: "news-anchor",
      text: "Introducing the next generation of refreshment. Just got bolder, smoother, and brewed to perfection.",
      voiceType: "Expressive Male Clone",
      audioUrl: "/audio/duff_stewie.wav",
    },
    {
      id: "passionate-speech",
      text: "So I want you to get up now. I want all of you to get up out of your chairs, and raise your voice — because change starts with you.",
      voiceType: "Deep Male Clone",
      audioUrl: "/audio/network_conan.wav",
    },
  ];

  const multilingualSamples = [
    {
      id: "hindi",
      language: "Indian 🇮🇳",
      text: "नमस्कार! हमारे मंच पर आपका स्वागत है।",
      audioUrl: "/audio/hindi.wav",
    },
    {
      id: "spanish",
      language: "Spanish 🇪🇸",
      text: "¡Hola! Bienvenido a nuestra plataforma.",
      audioUrl: "/audio/spanish.wav",
    },
    {
      id: "french",
      language: "French 🇫🇷",
      text: "Bonjour! Bienvenue sur notre plateforme.",
      audioUrl: "/audio/french.wav",
    },
    {
      id: "japanese",
      language: "Japanese 🇯🇵",
      text: "こんにちは！私たちのプラットフォームへようこそ。",
      audioUrl: "/audio/japanese.wav",
    },
  ];

  const handlePlay = (id: string, audioUrl: string) => {
    if (playingId === id) {
      const audio = document.getElementById(id) as HTMLAudioElement;
      audio?.pause();
      setPlayingId(null);
      return;
    }

    if (playingId) {
      const currentAudio = document.getElementById(
        playingId,
      ) as HTMLAudioElement;
      currentAudio?.pause();
      currentAudio.currentTime = 0;
    }

    const audio = document.getElementById(id) as HTMLAudioElement;
    if (audio) {
      audio
        .play()
        .then(() => {
          setPlayingId(id);
        })
        .catch((error) => {
          console.error("Audio playback failed:", error);
          alert(
            "Unable to play audio. Please check the audio file or try generating your own speech in the dashboard!",
          );
        });

      audio.onended = () => {
        setPlayingId(null);
      };

      audio.onerror = () => {
        setPlayingId(null);
      };
    }
  };
  return (
    <section className="border-b border-stone-200 bg-stone-50 py-20 sm:py-28">
      <div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
        <div className="mx-auto mb-14 max-w-xl text-center">
          <h2 className="mb-3 text-3xl font-bold tracking-tight text-stone-900">
            Hear it for yourself
          </h2>
          <p className="text-stone-500">
            Real audio samples generated by Vokl — natural speech and multilingual voice output.
          </p>
        </div>
        <div className="mb-12">
          <h3 className="mb-5 text-center text-lg font-semibold text-stone-800">
            Natural &amp; Expressive Speech
          </h3>
          <Card className="overflow-hidden border-stone-200 shadow-none">
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead className="bg-slate-50">
                  <tr>
                    <th className="px-6 py-4 text-left text-sm font-semibold text-slate-700">
                      Text Sample
                    </th>
                    <th className="px-6 py-4 text-left text-sm font-semibold text-slate-700">
                      Voice Type
                    </th>
                    <th className="px-6 py-4 text-center text-sm font-semibold text-slate-700">
                      Audio Output
                    </th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-200">
                  {naturalSpeechSamples.map((sample) => (
                    <tr key={sample.id} className="hover:bg-slate-50/50">
                      <td className="px-6 py-4 text-sm text-slate-600">
                        &ldquo;{sample.text}&rdquo;
                      </td>
                      <td className="px-6 py-4 text-sm font-medium text-slate-700">
                        {sample.voiceType}
                      </td>
                      <td className="px-6 py-4">
                        <div className="flex justify-center">
                          <Button
                            variant="outline"
                            size="sm"
                            className="gap-2 text-indigo-600 hover:bg-indigo-50 hover:text-indigo-700"
                            onClick={() =>
                              handlePlay(sample.id, sample.audioUrl)
                            }
                          >
                            {playingId === sample.id ? (
                              <>
                                <Pause className="h-4 w-4" />
                                Pause
                              </>
                            ) : (
                              <>
                                <Play className="h-4 w-4" />
                                Play
                              </>
                            )}
                          </Button>
                          {sample.audioUrl && (
                            <audio
                              id={sample.id}
                              src={sample.audioUrl}
                              preload="metadata"
                            />
                          )}
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </Card>
        </div>
        {/* Multilingual Support Demo */}
        <div>
          <h3 className="mb-5 text-center text-lg font-semibold text-stone-800">
            Multilingual Support
          </h3>
          <Card className="overflow-hidden border-stone-200 shadow-none">
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead className="bg-slate-50">
                  <tr>
                    <th className="px-6 py-4 text-left text-sm font-semibold text-slate-700">
                      Language
                    </th>
                    <th className="px-6 py-4 text-left text-sm font-semibold text-slate-700">
                      Text Sample
                    </th>
                    <th className="px-6 py-4 text-center text-sm font-semibold text-slate-700">
                      Audio Output
                    </th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-200">
                  {multilingualSamples.map((sample) => (
                    <tr key={sample.id} className="hover:bg-slate-50/50">
                      <td className="px-6 py-4 text-sm font-medium text-slate-700">
                        {sample.language}
                      </td>
                      <td className="px-6 py-4 text-sm text-slate-600">
                        &ldquo;{sample.text}&rdquo;
                      </td>
                      <td className="px-6 py-4">
                        <div className="flex justify-center">
                          <Button
                            variant="outline"
                            size="sm"
                            className="gap-2 text-indigo-600 hover:bg-indigo-50 hover:text-indigo-700"
                            onClick={() =>
                              handlePlay(sample.id, sample.audioUrl)
                            }
                          >
                            {playingId === sample.id ? (
                              <>
                                <Pause className="h-4 w-4" />
                                Pause
                              </>
                            ) : (
                              <>
                                <Play className="h-4 w-4" />
                                Play
                              </>
                            )}
                          </Button>
                          {sample.audioUrl && (
                            <audio
                              id={sample.id}
                              src={sample.audioUrl}
                              preload="metadata"
                              crossOrigin="anonymous"
                            />
                          )}
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </Card>
        </div>
        <div className="mt-10 text-center">
          <p className="mb-5 text-sm text-stone-500">
            Ready to create your own audio?
          </p>
          <Link href="/dashboard">
            <Button
              size="lg"
              className="cursor-pointer gap-2 bg-stone-900 text-white hover:bg-stone-800"
            >
              Start generating
            </Button>
          </Link>
        </div>
      </div>
    </section>
  );
}
